// Generated by CoffeeScript 1.12.6
(function() {
  var getBrowserLanguage, languages, translator;

  translator = null;

  languages = ["en", "uk", "ru"];

  $(document).ready(function() {
    translator = new Translator(getBrowserLanguage());
    return jQuery.getJSON("js/translator/literals.json", function(dict) {
      return translator.addDictionary(dict, true);
    });
  });

  getBrowserLanguage = function() {
    var blang, ind, lang;
    lang = "en";
    blang = navigator.language.slice(0, 2);
    ind = languages.indexOf(blang);
    if (ind >= 0) {
      lang = languages[ind];
    }
    return lang;
  };

}).call(this);
